First homework - Bazhenov Kirill
ok-technopolis-autumn-2022/Kirill_Bazhenov pull request #1
Opened 2022-09-30 17:26 UTC by Kirill06344

2022-09-30 17:40 UTC, fromanywhere reviewed
Тут всё нормально

Оставьте, пожалуйста, PR открытым, будем дорабатывать тут же после следующей лекции

2022-10-07 12:33 UTC, fromanywhere commented
Жду здесь aria

2022-10-10 08:46 UTC, fromanywhere requested changes

2022-10-10 08:46 UTC, fromanywhere commented on index.html
> +      <button class="button_select_all_tasks" role="button"></button>
раз есть тег, роль не нужна
а текста нет (а должен быть)

2022-10-10 08:46 UTC, fromanywhere commented on index.html
> +  <section class="tasks-button_group" role="radiogroup" aria-label="">
тут нужно придумать, что написать для людей в aria-label

2022-10-10 16:17 UTC, Kirill06344 commented on index.html
> +      <button class="button_select_all_tasks" role="button"></button>
Поправил

2022-10-10 16:17 UTC, Kirill06344 commented on index.html
> +  <section class="tasks-button_group" role="radiogroup" aria-label="">
Поправил

2022-10-10 17:05 UTC, fromanywhere approved these changes

2022-10-11 05:13 UTC, merged