add js
ok-technopolis-autumn-2022/Kirill_Bazhenov pull request #4
Opened 2022-11-21 00:10 UTC by Kirill06344

2022-11-21 00:37 UTC, Kirill06344 commented
Недоделал изменение числа + доролнительное задание.Обязательно доделаю завтра + разобью все на модули, попытаюсь почистить код, вообщем сделать грамотно, хотя понимания, как грамотно, практически нет + много дублирования, есть места, где не эффективно работает.Если посмотрите, напишите, пожалуйста, что критично неправильно сделано, как лучше поправить.

2022-11-21 09:55 UTC, fromanywhere requested changes
Предлагаю поставить eslint

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +const allButton = document.querySelector(`[id="button_all_tasks"]`);
getElemendById? Но лучше .js-button_all_tasks

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +let tasks = [];
const

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +        let li = ul.querySelector(`[id="${task.id}"]`);
const

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +        if (!checkbox.checked) {
Интересно, а можно было просто выбрать все элементы с анчекнутыми чекбоксами?

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +        li.style.display = '';
для этого придумали css и classList

2022-11-21 09:55 UTC, fromanywhere commented on src/index.js
> +    tasks = tasks.filter((value, inx) => inxs.indexOf(inx) === -1);
Я понимаю моду на иммутабельность, но может быть всё-таки splice?

2022-11-21 19:06 UTC, Kirill06344 commented
Постарался раскидать, что посчитал нужным по разным модулям, с помощью делегирования убрал дублирующийся код для фильтров(не знаю, насколько правильно, но по коду намного меньше получилось и эстетичнее).Убрал style и заменил на classList, поставил eslint.Доделал табличку с количеством itemов.Обязательно доделаю дополнительное задание.
Меня как-то очень беспокоит мой массив tasks.Мне пришлось растянуть его на несколько модулей и импортировать из одного в другой, что, наверное, не очень круто + попытался поправить с фильтром, но пока вообще не понял, как использовать здесь splice.Просто я специально собираю индексы во время итераци по массиву tasks, так как не могу же я во время прохода по коллекции удалять из нее элемента.Видимо, не до конца понял вашу мысль(

2022-11-22 10:15 UTC, fromanywhere commented on src/index.js
> +    tasks = tasks.filter((value, inx) => inxs.indexOf(inx) === -1);
> Просто я специально собираю индексы во время итераци по массиву tasks, так как не могу же я во время прохода по коллекции удалять из нее элемента.Видимо, не до конца понял вашу мысль(

Конечно же можете!
let i = tasks.length;
while (i--) { ...; if () { tasks.splice(i, 1) } }

Безопасно, потому что обратный перебор. Удаленный элемент уже не повлияет

2022-11-22 11:15 UTC, fromanywhere requested changes
Критично — поправить функционал работы счетчика
Остальное надо бы тоже сделать, в частности eslint
Неудивительно, что здесь вермишель — в этом и заключается смысл этой работы, чтобы показать, что строить интерфейсы вот так вот в лоб поверх dom довольно нетривиально. Это возможно, но есть более стройные способы — в сл. работе

2022-11-22 11:15 UTC, fromanywhere commented on src/updateItemsLeft.js
> +  itemsCount.textContent = String(number) + ' ' + words[1] + ' ' + words[2];
Тут меняется структура дерева при изменениях, и на первом добавлении всё прыгает
Кстати, попробуйте тут использовать template literals `${number} ${words[1]} ${words[2]}`
Кстати, брать локализацию из дерева не очень классно — как быть с 1 item left vs 2 items left?

2022-11-22 11:15 UTC, fromanywhere commented on package.json
> +    "eslint": "^8.28.0",
а как запустить проверку?

2022-11-22 11:15 UTC, fromanywhere commented on src/updateItemsLeft.js
> +  itemsCount.textContent = String(number) + ' ' + words[1] + ' ' + words[2];
Сломался счетчик при отметке задачи как завершенной
Вот тут можно посмотреть, как оно бы должно работать https://todomvc.com/

2022-11-22 11:15 UTC, fromanywhere commented on src/createLi.js
> +  buttonDelete.addEventListener('click', deleteTask);
делегирование

2022-11-22 11:15 UTC, fromanywhere commented on src/createLi.js
> +  const hiddenInput = document.createElement('input');
А как попасть в состояние редактирования?

2022-11-22 11:15 UTC, fromanywhere commented on src/index.js
> +document.querySelector('.tasks-button_group').onclick = function (event) {
так конечно можно, но лучше addEventListener

2022-11-22 11:15 UTC, fromanywhere commented on src/index.js
> +  if (target.tagName !== 'LABEL') {
лучше бы тут не по тегу, а по классу

2022-11-22 11:15 UTC, fromanywhere commented on index.html
> +        aria-label="Show all tasks"
по умолчанию all выбран, т.е. checked

2022-11-22 11:15 UTC, fromanywhere commented on src/createLi.js
> +    let index = tasks.map(el => el.id).indexOf(name.id);
tasks.findIndex?

2022-11-22 11:15 UTC, fromanywhere commented on src/index.js
> +  if (target.tagName !== 'LABEL') {
По-хорошему тут должен быть change от радиокнопки

2022-11-24 18:48 UTC, Kirill06344 commented on src/updateItemsLeft.js
> +  itemsCount.textContent = String(number) + ' ' + words[1] + ' ' + words[2];
он у меня не сломался, я просто думал, что он работает по-другому)То есть он просто всегда показывает, сколько у нас не заврешенных(не отмеченных задач) в независимости от фильтра.

2022-11-24 18:50 UTC, Kirill06344 commented on package.json
> +    "eslint": "^8.28.0",
я надеюсь правильно понял, что нужно добавить скрипт в package.json и отслеживать .eslintsrc.json. Просто у меня вроде проверка работает и все норм, из терминала запускаю

2022-11-24 19:45 UTC, Kirill06344 commented on index.html
> +        aria-label="Show all tasks"
поправил

2022-11-24 19:45 UTC, Kirill06344 commented on src/createLi.js
> +    let index = tasks.map(el => el.id).indexOf(name.id);
поправил

2022-11-24 19:49 UTC, Kirill06344 commented on src/index.js
> +document.querySelector('.tasks-button_group').onclick = function (event) {
поправил

2022-11-24 19:52 UTC, Kirill06344 commented on src/index.js
> +  if (target.tagName !== 'LABEL') {
поменял на класс, но не понял про change

2022-11-24 19:55 UTC, Kirill06344 commented on src/createLi.js
> +  const hiddenInput = document.createElement('input');
вот это я на самом деле до сих пор не понял, для чего вообще нужно.Там это показывали, когда мы только html делали.Мне бы сначала цель понять, а потом я обязательно поправлю

2022-11-24 20:51 UTC, Kirill06344 commented
поправил счетчик.Сделал делегирование для deleteButton.Не совсем проникся для чего оно нам здесь, пока не могу осознать.То есть для 3 фильтров я понял, но здесь не очень.Повесил на ul

2022-11-24 20:51 UTC, Kirill06344 commented on src/createLi.js
> +  buttonDelete.addEventListener('click', deleteTask);
поправил

2022-11-25 09:10 UTC, fromanywhere commented on src/createLi.js
> +  const hiddenInput = document.createElement('input');
Ну, типа, предполагается, что мы можем захотеть как-то редактировать уже добавленные тудушки. И раз уже изначально они рисуются в нередактируемом поле, то нужно как-то переходить в режим редактирования — например, заменять просто вывод текста полем с тектом для редактирования. Тут можно обсуждать, как это лучше сделать — по клику, или, может, по двойному клику. 

Но вообще пока нет ни одной работы, в которой хоть кто-то бы это сделал

2022-11-25 09:12 UTC, fromanywhere commented on src/index.js
> +  if (target.tagName !== 'LABEL') {
А если изменение будет вызвано не кликом, а клавиатурной навигацией? Я в принципе готов поверить, что клик браузер все равно триггернет, но на самом деле это костыль, и слушать нужно «изменение радиокнопки», а не «клик на радиокнопку»

2022-11-25 09:16 UTC, fromanywhere approved these changes
Зачтено

2022-11-25 09:16 UTC, fromanywhere commented on src/index.js
> +  while(i--) {
Вообще идея была в том, чтобы не создавать const inxs = [].
Здесь можно было const task = exportTasks.arr[i], тогда вся логика из forEach уезжает сюда, тогда только одна итерация и нет промежуточного массива

2022-11-25 09:16 UTC, fromanywhere commented on src/updateItemsLeft.js
> +  return (number === 1) ? 'item' : 'items';
это хорошо

2022-11-25 09:26 UTC, Kirill06344 commented
Только не закрывайте, я хотел бы еще редактирование доделать

2022-11-27 14:48 UTC, merged